name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

#env:
#  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/source
        requirements_path: ./requirements.txt
        target_branch: gh-pages
